name: Times Ranking Bot

on:
  schedule:
   # 毎週日曜日の21:00 (JST) に実行する設定（コメントアウトして無効化）
    # - cron: '0 12 * * 0'
    
    # 毎週土曜日の16:00 (JST) に実行する設定 (UTCでは土曜日の07:00)
    - cron: '0 7 * * 6'
  
  # 手動で好きな時に実行できるボタンを追加
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Pythonのセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ライブラリのインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Botの実行 (main.py)
        # Step 3で登録したSecretsを、環境変数としてプログラムに渡す
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: python main.py
